baseURL: 'http://example.org/'
languageCode: en-us
title: guides.lw1.at
theme: hugo-xmin
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    tabWidth: 4
    noClasses: true
    style: github
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"
