baseURL: 'https://guides.lw1.at/'
languageCode: en-us
title: guides.lw1.at
enableGitInfo: true
enableRobotsTXT: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    tabWidth: 4
    noClasses: false
    style: dracula
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
permalinks:
  guide: /:slug/
taxonomies:
  category: categories
#ignoreFiles:
#  - \.mp4$
#  - \.webm$
